### ISSUE TITLE
Is not working

### ISSUE THREAD

**Issue by thkaza** [pranaygp/vscode-css-peek#56]
After installing the extension I got this error in the OUTPUT.

```
c:\Users\XXX\.vscode\extensions\pranaygp.vscode-css-peek-2.2.0\server\node_modules\vscode-css-languageservice\lib\umd\parser\cssSymbolScope.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { 
                                                                                                                                                           

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:678:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[Info  - 11:40:39] Connection to server got closed. Server will restart.
c:\Users\XXX\.vscode\extensions\pranaygp.vscode-css-peek-2.2.0\server\node_modules\vscode-css-languageservice\lib\umd\parser\cssSymbolScope.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) {
```

**Comment by mcquaye** [comment]
does not work on my version of vscode.

**Comment by pranaygp** [comment]
Can you check if this is still an issue in CSS Peek version 3.2.6
