### ISSUE TITLE
The CSS Peek server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by djdakta** [pranaygp/vscode-css-peek#69]
VS Code for Mac:
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

I'm getting this error after VS Code is open for a few minutes:
The CSS Peek server crashed 5 times in the last 3 minutes. The server will not be restarted.
Can I change something in my settings so I don't have this issue any more or?

Thx for your support.

**Comment by MoonCheung** [comment]
I have encountered the same situation, how to solve it?

**Comment by pranaygp** [comment]
Is this still happening for you? I can't reproduce this issue. Please send me a `.zip` of a test project which I can open with CSS Peek and has this issue.

Also, make sure you're using CSS Peek 3.3.0+

**Comment by kpinkerman** [comment]
This issue has occurred for me.  Here's the stack:
Error: Cannot find module '/Users/xxxxxx/.vscode/extensions/pranaygp.vscode-css-peek-4.0.2/server/out/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
    at Module._load (internal/modules/cjs/loader.js:737:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1103:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
