### ISSUE TITLE
CSS Peek fails to start with VSCode 1.45+

### ISSUE THREAD

**Issue by willstocks** [pranaygp/vscode-css-peek#80]
With VSCode 1.45.0+, I've been seeing the following upon launching VSCode and css-peek then not working

![image](https://user-images.githubusercontent.com/43744514/82067678-f538fe00-96c8-11ea-8a34-c3666b72ea88.png)

```
[Error - 16:23:20] Starting client failed
Error: spawn C:\Users\WillStocks\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[Error - 16:23:20] Starting client failed
Error: spawn C:\Users\WillStocks\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
[Error - 16:23:20] Starting client failed
Error: spawn C:\Users\WillStocks\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

I'm running Windows 10 Enterprise 1909

**Comment by pranaygp** [comment]
Just pushed a fix for this. Update to CSS Peek 3.2.6
